---
- name: Eliminar usuarios definidos desde el Survey
  hosts: all
  become: true
  vars:
    # Esta variable será sobreescrita por el Survey
    usuarios_a_eliminar: []
  tasks:
    - name: Eliminar usuarios especificados
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop: "{{ usuarios_a_eliminar }}"
      ignore_errors: true
