---
- name: Eliminar usuario de forma automatica
  hosts: all
  become: true
  tasks:
    - name: Eliminar usuario si existe
      ansible.builtin.user:
        name: gerardo
        state: absent
        remove: yes 
